"""
Report generation service for PageGuard.
Generates compliance reports from scan results.
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_text_report(site_url: str, scan_data: dict, violations: list) -> str:
    """Generate a plain text compliance report."""
    lines = [
        "=" * 60,
        "PageGuard Web Accessibility Compliance Report",
        "=" * 60,
        f"Website: {site_url}",
        f"Scan Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"Compliance Score: {scan_data.get('score', 'N/A')}/100",
        f"Pages Scanned: {scan_data.get('pages_scanned', 0)}",
        f"Total Violations: {scan_data.get('total_violations', 0)}",
        "",
        "Violation Breakdown:",
        f"  Critical: {scan_data.get('critical_count', 0)}",
        f"  Serious:  {scan_data.get('serious_count', 0)}",
        f"  Moderate: {scan_data.get('moderate_count', 0)}",
        f"  Minor:    {scan_data.get('minor_count', 0)}",
        "",
        "-" * 60,
        "VIOLATIONS DETAIL",
        "-" * 60,
    ]
    
    for i, v in enumerate(violations, 1):
        lines.extend([
            f"\n{i}. [{v.get('severity', 'unknown').upper()}] {v.get('rule_name', 'Unknown Rule')}",
            f"   WCAG: {v.get('wcag_criteria', 'N/A')}",
            f"   Page: {v.get('page_url', 'N/A')}",
            f"   Description: {v.get('description', '')}",
            f"   Element: {v.get('element_html', 'N/A')[:100]}",
            f"   Fix: {v.get('fix_suggestion', 'See WCAG guidelines')[:200]}",
        ])
    
    lines.extend([
        "",
        "=" * 60,
        "ADA Title II Compliance Deadline: April 24, 2026",
        "Non-compliance penalties: up to $150,000 per violation",
        "Report generated by PageGuard (https://pageguard.dev)",
        "=" * 60,
    ])
    
    return "\n".join(lines)
